name: dplanet
description: A planet style RSS aggregator with a PostGres backend.
version: 0.0.1
#homepage: https://www.example.com
author: daftspaniel <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  postgresql2: any

dev_dependencies:
  test: ^0.12.0
